// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Context;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230926204645_InitialCreate3")]
    partial class InitialCreate3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Controllers.OtoparkArac", b =>
                {
                    b.Property<int>("ArabaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArabaId"));

                    b.Property<decimal?>("ArabaFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ArabaSinif")
                        .HasColumnType("int");

                    b.Property<bool>("ArabaYikama")
                        .HasColumnType("bit");

                    b.Property<int?>("BagajHacmi")
                        .HasColumnType("int");

                    b.Property<int>("BeygirGucu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CikisZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GirisZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LastikDegisimi")
                        .HasColumnType("bit");

                    b.Property<string>("ModelAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelYili")
                        .HasColumnType("int");

                    b.Property<bool>("OtomatikPilot")
                        .HasColumnType("bit");

                    b.Property<decimal?>("OtoparkUcreti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("YedekLastik")
                        .HasColumnType("bit");

                    b.HasKey("ArabaId");

                    b.ToTable("OtoparkAracLists");
                });
#pragma warning restore 612, 618
        }
    }
}
